#ifndef CLIPBOARDSYNCCORE_GLOBAL_H
#define CLIPBOARDSYNCCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLIPBOARDSYNCCORE_LIBRARY)
#  define CLIPBOARDSYNCCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLIPBOARDSYNCCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLIPBOARDSYNCCORE_GLOBAL_H
